### ISSUE TITLE
Make contract interactions mockable

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/ethcontract-rs#424] opened 2020-12-18 16:40 UTC
When using ethcontracts in other libraries and writing unit tests for components that interact with smart contracts, it is currently quite cumbersome to factor the interactions in a way that make the easily mockable for unit tests (basically it requires creating trait that exposes the same methods but can be mocked).

Maybe ethcontracts could natively offer all generated smart contracts as traits. `deployed`, `new` or `at` would then return the concrete instance we have today, but consumers could also easily create fake implementations for unit tests (maybe there could even be a default stub provided by ethcontracts or we expose mockall).

**Comment by taminomara** [comment] 2021-07-05 12:09
This is a duplicate of #83.

**Closed as completed by taminomara** 2021-07-05 12:09 UTC
Labels: duplicate
